### ISSUE TITLE
Server is crashing on Ubuntu, vscode-insider

### ISSUE THREAD

**Issue by shanlalit** [pheen/fuzzy_ruby_server#1]
Hi,

This extension looks fun, after installation it is giving below mentioned error in output panel. FYI I'm also using 'Ruby LSP' extension.

I hope this would help fix the issue.

/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/bin/fuzzy: 1: Syntax error: word unexpected (expecting ")")
[Info  - 16:44:41] Connection to server got closed. Server will restart.
/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/bin/fuzzy: 1: Syntax error: word unexpected (expecting ")")
[Info  - 16:44:41] Connection to server got closed. Server will restart.
/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/bin/fuzzy: 1: Syntax error: word unexpected (expecting ")")
[Info  - 16:44:41] Connection to server got closed. Server will restart.
[Error - 16:44:41] Client Fuzzy Ruby Language Server: connection to server is erroring. Shutting down server.
[Info  - 16:44:41] Connection to server got closed. Server will restart.
/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/bin/fuzzy: 1: Syntax error: word unexpected (expecting ")")
/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/bin/fuzzy: 1: Syntax error: word unexpected (expecting ")")
[Error - 16:44:41] The Fuzzy Ruby Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 16:44:41] Stopping server failed
Error: Connection to server got closed. Server will not be restarted.
	at Ou.handleConnectionClosed (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:39:10208)
	at Ou.handleConnectionClosed (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:39:79988)
	at t (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:39:9535)
	at As.invoke (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:5:14324)
	at Dr.fire (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:5:15093)
	at bt (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:6:6355)
	at As.invoke (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:5:14324)
	at Dr.fire (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:5:15093)
	at Gi.fireClose (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:6:523)
	at Socket.<anonymous> (/home/shanlalit/.vscode-insiders/extensions/blinknlights.fuzzy-ruby-server-0.6.3/client/out/extension.js:6:1249)
	at Socket.emit (node:events:513:28)
	at Pipe.<anonymous> (node:net:757:14)

**Comment by shanlalit** [comment]
Here is how I made it work.

removed 'fuzzy'
renamed 'fuzzy_x86_64-unknown-linux-gnu' to 'fuzzy'

Restarted vscode. Indexed Gems and workspace and now the go to definition is working fine.

Thank you for the extension.

**Comment by pheen** [comment]
Hey @shanlalit ! Thanks for trying it out and reporting the issue. The conditional for checking whether to use `fuzzy` or `fuzzy_x86...` is [here](https://github.com/pheen/fuzzy_ruby_server/blob/f8618e4bdb8769d1a49c69da4e9bcfead6e932ab/client/src/extension.ts#L47-L52) in Typescript.

- [ ] Updating that condition so it confirms it is Mac OS and calls `fuzzy`, or every other scenario call `fuzzy_x86...`, seems reasonable

**Comment by shanlalit** [comment]
Hi @pheen,

remoteName doesn't tel you the OS, it is to detect if the vs-code is running in web or not (based on quick read). 

I found a Stack-overflow discussion on this --  
https://stackoverflow.com/questions/63882661/how-to-get-host-operating-system-name-from-visual-studio-code-extension

I think using node built-in  https://nodejs.org/api/os.html#os_os_platform would be more suitable. 

What you think?
