### ISSUE TITLE
stream did not contain valid UTF-8 (vscode/Pop!_OS)

### ISSUE THREAD

**Issue by pawlik** [pheen/fuzzy_ruby_server#11]
Hey, reading about the project got me excited but it crashes on me: 

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: InvalidData, message: "stream did not contain valid UTF-8" }', src/persistence.rs:470:58
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
   2: core::result::unwrap_failed
             at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/result.rs:1651:5
   3: fuzzy::persistence::Persistence::reindex_modified_files
   4: <fuzzy::Backend as tower_lsp::LanguageServer>::initialize::{{closure}}::{{closure}}
   5: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run
   9: tokio::runtime::context::scoped::Scoped<T>::set
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  13: tokio::runtime::task::harness::Harness<T,S>::poll
  14: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

When I try to find a definition after that I get such a message in the log: 

```
[2023-11-23T16:23:13Z INFO  fuzzy::persistence] No highlight usages docs found
[2023-11-23T16:23:13Z INFO  fuzzy::persistence] No usages docs found
[2023-11-23T16:32:32Z INFO  fuzzy::persistence] No usages docs found
[2023-11-23T16:32:38Z INFO  fuzzy::persistence] No usages docs found
```

None of the settings seem to influence the behavior. Please advise :) 

edit: I tried running `RUST_BACKTRACE=full code` but this env seems to not reach the extension, the backtrace is the same.

**Comment by pheen** [comment]
I'm not sure sorry. If you're using VSCode you can clone the repo and debug by running the extension via VSCode debug tools https://github.com/pheen/fuzzy_ruby_server/blob/master/client/src/extension.ts
